image: golang:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - go build ./...

lint:
  stage: build
  script:
    - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin
    - golangci-lint run ./...

test_job:
  stage: test
  script:
    - go install github.com/onsi/ginkgo/v2/ginkgo@latest
    - ginkgo -r --randomize-suites --fail-on-pending --cover --trace --race --progress --skip="Stress" 
    - go test -coverprofile=cover.out ./...
    - go tool cover -func=cover.out > coverage.out
    - tail coverage.out
